name: Test secret

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Publish package
      env:
        PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload --repository-url ${{ vars.PYPI_URL }} dist/* --verbose -u $PYPI_USERNAME -p $PYPI_PASSWORD


        
        
