name: Test secret

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install twine
    - name: Print
      run: |
        echo ${{ vars.PYPI_URL }}
#     - name: Publish package
#       env:
#         PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
#         PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
#       run: |
#         twine upload --repository-url ${{ vars.PYPI_URL }} dist/* --verbose -u $PYPI_USERNAME -p $PYPI_PASSWORD

        
        
        
